const state={settings:{},patterns:[],allowed:[],blocks:[],characters:new Set(),binding:'independent',sites:[],results:[],history:[],visibleHistory:[],selectedHistory:new Set(),ready:false,running:false,paused:false,previewTimer:null,saveTimer:null,historyRefreshTimer:null};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function toast(message,type=''){const el=$('toast');el.textContent=message;el.className=`toast ${type} show`;clearTimeout(el._timer);el._timer=setTimeout(()=>{el.className='toast'},4200)}
function setPage(name){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===name));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${name}`));const meta={rules:['生成规则','用积木自由组合域名结构'],run:['运行设置','连接 Chrome、选择网站并设置查询方式'],results:['可注册结果','仅显示名称完全一致且可注册的 .com 域名'],history:['已查询记录','查看、导出或删除历史记录，删除后可以重新查询']}[name];$('pageTitle').textContent=meta[0];$('pageSubtitle').textContent=meta[1];if(name==='history')refreshHistory()}
function setStatus(message,kind='info'){const pill=$('readyPill');pill.textContent=message;pill.className=`pill ${kind}`}
function updateControls(){const canStart=state.ready&&!state.running;['topStart','bottomStart'].forEach(id=>$(id).disabled=!canStart);$('topPause').disabled=!state.running||state.paused;$('topResume').disabled=!state.running||!state.paused;$('topStop').disabled=!state.running;$('connectChrome').disabled=state.running;$('reconnectPage').disabled=state.running;$('deleteSelectedHistory').disabled=state.running||state.selectedHistory.size===0;$('clearHistory').disabled=state.running||state.history.length===0}

function renderCharacters(){const pool=$('characterPool');pool.innerHTML='';state.allowed.forEach(char=>{const b=document.createElement('button');b.className=`char-chip${state.characters.has(char)?' selected':''}`;b.textContent=char;b.dataset.char=char;pool.appendChild(b)})}
function blockLabel(kind){return {fixed:'固定文字',common:'常用规律',custom:'自定义规律',unlimited:'不限随机'}[kind]||kind}
function blockColor(kind){return ['common','custom','fixed','unlimited'].includes(kind)?kind:'common'}
function renderBlocks(){const wrap=$('blockComposer');if(!state.blocks.length){wrap.innerHTML='<div class="empty-composer">还没有组合块，请从上方添加一个。</div>';schedulePreview();return}wrap.innerHTML='';state.blocks.forEach((block,index)=>{if(index){const plus=document.createElement('div');plus.className='block-plus';plus.textContent='+';wrap.appendChild(plus)}const card=document.createElement('div');card.className=`block-card ${blockColor(block.kind)}`;let valueControl='';if(block.kind==='common'){valueControl=`<select class="block-value" data-index="${index}" data-field="value">${state.patterns.map(p=>`<option value="${p}"${p===block.value?' selected':''}>${p}</option>`).join('')}</select>`}else if(block.kind==='custom'){valueControl=`<input class="block-value" data-index="${index}" data-field="value" value="${esc(block.value||'ABCDDDD')}" placeholder="例如 ABCDDDD">`}else if(block.kind==='fixed'){valueControl=`<input class="block-value" data-index="${index}" data-field="value" value="${esc(block.value||'')}" placeholder="固定文字">`}else{valueControl=`<input class="block-value" data-index="${index}" data-field="length" type="number" min="1" max="63" value="${Number(block.length)||4}">`}const hint={fixed:'内容原样写入域名',common:'从常用规律中选择',custom:'自由输入占位规律',unlimited:'选择“不限”随机部分位数'}[block.kind];card.innerHTML=`<div class="block-card-head"><span>⠿ ${blockLabel(block.kind)}</span><span class="block-actions"><button class="icon-btn" data-action="duplicate" data-index="${index}" title="复制">▣</button><button class="icon-btn" data-action="delete" data-index="${index}" title="删除">⌫</button></span></div><div class="block-card-body"><select data-index="${index}" data-field="kind"><option value="fixed"${block.kind==='fixed'?' selected':''}>固定文字</option><option value="common"${block.kind==='common'?' selected':''}>常用规律</option><option value="custom"${block.kind==='custom'?' selected':''}>自定义规律</option><option value="unlimited"${block.kind==='unlimited'?' selected':''}>不限随机</option></select>${valueControl}<div class="block-hint">${hint}</div><div class="move-row"><button data-action="left" data-index="${index}"${index===0?' disabled':''}>← 左移</button><button data-action="right" data-index="${index}"${index===state.blocks.length-1?' disabled':''}>右移 →</button></div></div>`;wrap.appendChild(card)});schedulePreview()}
function addBlock(kind,value){const defaults={fixed:{kind:'fixed',value:value??'abc',length:1},common:{kind:'common',value:value??'AAA',length:1},custom:{kind:'custom',value:value??'ABCDDDD',length:1},unlimited:{kind:'unlimited',value:'',length:4}};state.blocks.push(defaults[kind]);renderBlocks();scheduleSave()}
function switchBlockKind(block,kind){const old=block.kind;block.kind=kind;if(kind==='common'&&!state.patterns.includes(String(block.value||'').toUpperCase()))block.value='AAA';if(kind==='custom'&&old==='common')block.value=String(block.value||'AAA').toUpperCase();if(kind==='fixed'&&old!=='fixed')block.value='';if(kind==='unlimited')block.length=Number(block.length)||4}
function rulePayload(){return {characters:[...state.characters],blocks:state.blocks.map(b=>({...b,length:Number(b.length)||1})),binding_mode:state.binding}}
function previewDescription(){return state.blocks.map(b=>b.kind==='fixed'?(b.value||'固定'):b.kind==='unlimited'?`随机${b.length}位`:(b.value||'规律')).join(' + ')}
function schedulePreview(){clearTimeout(state.previewTimer);state.previewTimer=setTimeout(refreshPreview,140)}
async function refreshPreview(){if(!window.pywebview?.api)return;const result=await window.pywebview.api.preview(rulePayload());const bar=$('previewBar');if(result.ok){bar.classList.remove('error');$('previewPieces').textContent=previewDescription()+' →';$('previewDomain').textContent=result.samples[0];$('previewLength').textContent=`名称长度 ${result.length} / 63`;$('footerSpace').textContent=Number(result.space).toLocaleString('zh-CN')+' 个'}else{bar.classList.add('error');$('previewPieces').textContent=result.message;$('previewDomain').textContent='';$('previewLength').textContent='';$('footerSpace').textContent='—'}}

function collectSettings(){return {...state.settings,...rulePayload(),site_name:$('siteName').value.trim(),site_url:$('siteUrl').value.trim(),sites:state.sites,preferred_page_url:$('pageChoice').value,interval:$('interval').value,retry_interval:$('retryInterval').value,limit_tests_enabled:$('limitTestsEnabled').checked,limit_tests:$('limitTests').value,limit_found_enabled:$('limitFoundEnabled').checked,limit_found:$('limitFound').value,run_until_stopped:$('runUntilStopped').checked,excel_path:$('excelPath').value.trim(),history_excel_path:$('historyExcelPath').value.trim()}}
function scheduleSave(){clearTimeout(state.saveTimer);state.saveTimer=setTimeout(async()=>{if(window.pywebview?.api)await window.pywebview.api.save_settings(collectSettings())},400)}
function applySettings(s){state.settings=s;state.characters=new Set(s.characters||state.allowed);state.blocks=(s.blocks||[{kind:'common',value:'AAA',length:1}]).map(b=>({...b,length:Number(b.length)||1}));state.binding=s.binding_mode||'independent';state.sites=s.sites||[];$('siteName').value=s.site_name||'';$('siteUrl').value=s.site_url||'';$('interval').value=s.interval||'5';$('retryInterval').value=s.retry_interval||'10';$('limitTestsEnabled').checked=!!s.limit_tests_enabled;$('limitTests').value=s.limit_tests||'10000';$('limitFoundEnabled').checked=!!s.limit_found_enabled;$('limitFound').value=s.limit_found||'100';$('runUntilStopped').checked=!!s.run_until_stopped;$('excelPath').value=s.excel_path||'';$('historyExcelPath').value=s.history_excel_path||'';renderSites(s.site_name);renderCharacters();renderBlocks();renderBinding();$('footerInterval').textContent=`${s.interval||5} 秒`}
function renderBinding(){document.querySelectorAll('[data-binding]').forEach(b=>b.classList.toggle('active',b.dataset.binding===state.binding))}
function renderSites(selectedName){$('siteSelect').innerHTML=state.sites.map(s=>`<option value="${esc(s.name)}"${s.name===selectedName?' selected':''}>${esc(s.name)}</option>`).join('')}
function renderPatterns(){const wrap=$('quickPatterns');wrap.innerHTML='';const unlimited=document.createElement('button');unlimited.textContent='不限';unlimited.dataset.quick='unlimited';wrap.appendChild(unlimited);state.patterns.forEach(p=>{const b=document.createElement('button');b.textContent=p;b.dataset.quick=p;wrap.appendChild(b)});const custom=document.createElement('button');custom.textContent='＋ 自定义规律';custom.dataset.quick='custom';wrap.appendChild(custom)}
function siteDisplay(value){try{return new URL(value).hostname}catch{return value||'历史记录'}}
function formatTime(value){if(!value)return'';const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString('zh-CN',{hour12:false})}
function renderResults(){const q=$('resultSearch').value.trim().toLowerCase();const rows=state.results.filter(r=>!q||Object.values(r).some(v=>String(v).toLowerCase().includes(q)));$('resultTotal').textContent=state.results.length;$('resultFound').textContent=$('foundCount').textContent;const body=$('resultBody');if(!rows.length){body.innerHTML='<tr><td colspan="5" class="empty-row">还没有符合条件的可注册域名</td></tr>';return}body.innerHTML=rows.map(r=>`<tr><td class="domain-cell">${esc(r.domain)}</td><td>${esc(r.pattern)}</td><td>${esc(siteDisplay(r.site))}</td><td>${esc(formatTime(r.time))}</td><td><span class="status-ok">可注册</span></td></tr>`).join('')}

function historyStatusClass(status){if(status==='exact_available')return'available';if(status==='exact_unavailable')return'unavailable';if(status==='query_failed'||status==='query_started')return'warning';return'neutral'}
function renderHistory(){const q=$('historySearch').value.trim().toLowerCase(),status=$('historyStatus').value;state.visibleHistory=state.history.filter(r=>(!status||r.status===status)&&(!q||[r.domain,r.status_label,r.pattern,r.site,r.detail].some(v=>String(v||'').toLowerCase().includes(q))));$('historyTotal').textContent=state.history.length;$('historySelected').textContent=state.selectedHistory.size;$('historyFilterCount').textContent=`${state.visibleHistory.length} 条记录`;const visible=state.visibleHistory.map(r=>r.domain);$('historyCheckAll').checked=visible.length>0&&visible.every(d=>state.selectedHistory.has(d));$('historyCheckAll').indeterminate=visible.some(d=>state.selectedHistory.has(d))&&!$('historyCheckAll').checked;const body=$('historyBody');if(!state.visibleHistory.length){body.innerHTML='<tr><td colspan="6" class="empty-row">没有符合当前筛选条件的已查询记录</td></tr>'}else{body.innerHTML=state.visibleHistory.map(r=>`<tr><td class="select-col"><input type="checkbox" data-history-domain="${esc(r.domain)}"${state.selectedHistory.has(r.domain)?' checked':''}></td><td class="domain-cell">${esc(r.domain)}</td><td><span class="history-status ${historyStatusClass(r.status)}">${esc(r.status_label)}</span></td><td>${esc(r.pattern)}</td><td>${esc(siteDisplay(r.site))}</td><td>${esc(formatTime(r.time))}</td></tr>`).join('')}updateControls()}
function applyHistoryResponse(result){state.history=result.history||[];state.results=result.results||state.results;const current=new Set(state.history.map(r=>r.domain));state.selectedHistory=new Set([...state.selectedHistory].filter(d=>current.has(d)));renderHistory();renderResults()}
async function refreshHistory(){if(!window.pywebview?.api)return;const result=await window.pywebview.api.history_state();if(result.ok)applyHistoryResponse(result)}
function scheduleHistoryRefresh(){if(!$('page-history').classList.contains('active'))return;clearTimeout(state.historyRefreshTimer);state.historyRefreshTimer=setTimeout(refreshHistory,120)}
function appendLog(text){const log=$('runLog');const time=new Date().toLocaleTimeString('zh-CN',{hour12:false});log.textContent+=(log.textContent?'\n':'')+`[${time}] ${text}`;log.scrollTop=log.scrollHeight}

async function connectChrome(){const url=$('siteUrl').value.trim();if(!url){toast('请先填写查询网址','error');return}setStatus('正在连接 Chrome…','running');$('connectChrome').disabled=true;const result=await window.pywebview.api.connect_browser({site_url:url,preferred_page_url:$('pageChoice').value});$('connectChrome').disabled=false;if(!result.ok){state.ready=false;setStatus('Chrome 未连接','info');$('connectionDetail').textContent=result.message;toast(result.message,'error');updateControls();return}state.ready=!!result.ready;$('connectionDetail').textContent=result.selected_url?`已连接：${result.selected_url}`:result.message;$('pageChoice').innerHTML=(result.pages||[]).map((p,i)=>`<option value="${esc(p.url)}"${p.url===result.selected_url?' selected':''}>${i+1}. ${esc(p.title||'未命名网页')} — ${esc(p.url)}</option>`).join('')||'<option value="">没有找到网页</option>';setStatus(result.message,state.ready?'ready':'info');if(result.verification_required)toast('请在 Chrome 中手动完成人机验证，然后再次连接。','error');updateControls();scheduleSave()}
async function startSearch(){const result=await window.pywebview.api.start_search(collectSettings());if(!result.ok){toast(result.message,'error');return}state.running=true;state.paused=false;$('checkedCount').textContent='0';$('foundCount').textContent='0';$('resultFound').textContent='0';$('currentDomain').textContent='正在连接…';$('footerTask').textContent='正在启动查询';setStatus('正在启动…','running');updateControls();appendLog('开始查询')}
async function pauseSearch(){const result=await window.pywebview.api.pause_search();if(!result.ok){toast(result.message,'error');return}state.paused=true;updateControls();setStatus('已暂停，可修改规则后继续','info')}
async function resumeSearch(){const result=await window.pywebview.api.resume_search(collectSettings());if(!result.ok){toast(result.message,'error');return}state.paused=false;updateControls();setStatus('新规则已提交，正在继续','running');appendLog('继续查询；已读取当前界面的最新规则')}
async function stopSearch(){await window.pywebview.api.stop_search();$('footerTask').textContent='正在停止；Chrome 保持原样';setStatus('正在停止…','running')}

window.handleBackendEvent=function(event){const {type,payload}=event;if(type==='status'){setStatus(payload.message,'running');appendLog(payload.message)}else if(type==='current'){$('currentDomain').textContent=payload.domain;$('footerTask').textContent=`正在查询 ${payload.domain}`;scheduleHistoryRefresh()}else if(type==='progress'){$('checkedCount').textContent=payload.checked;$('foundCount').textContent=payload.found;$('resultFound').textContent=payload.found;appendLog(`已检测 ${payload.checked} 个`);scheduleHistoryRefresh()}else if(type==='found'){state.results.unshift({domain:payload.domain,pattern:payload.pattern,site:$('siteUrl').value,time:payload.checked_at});renderResults();appendLog(`已保存 ${payload.domain}`);toast(`找到可注册域名：${payload.domain}`,'success');scheduleHistoryRefresh()}else if(type==='verification'){setStatus('需要人工验证','info');appendLog(payload.message);toast('请在 Chrome 中手动完成人机验证，完成后软件会继续。','error')}else if(type==='finished'){state.running=false;state.paused=false;setStatus('准备就绪','ready');$('footerTask').textContent='任务已结束';appendLog(payload.message);updateControls();refreshHistory()}else if(type==='error'){state.running=false;state.paused=false;if(String(payload.message).includes('Chrome')||String(payload.message).includes('浏览器'))state.ready=false;setStatus('查询已停止','info');appendLog(`错误：${payload.message}`);toast(payload.message,'error');updateControls();refreshHistory()}}

function bindRuleEvents(){document.querySelectorAll('[data-char-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.charAction;if(a==='all')state.characters=new Set(state.allowed);if(a==='letters')state.characters=new Set(state.allowed.filter(c=>/[a-z]/.test(c)));if(a==='numbers')state.characters=new Set(state.allowed.filter(c=>/[0-9]/.test(c)));if(a==='clear')state.characters.clear();renderCharacters();schedulePreview();scheduleSave()}));$('characterPool').addEventListener('click',e=>{const b=e.target.closest('[data-char]');if(!b)return;const c=b.dataset.char;state.characters.has(c)?state.characters.delete(c):state.characters.add(c);renderCharacters();schedulePreview();scheduleSave()});document.querySelectorAll('[data-add-block]').forEach(b=>b.addEventListener('click',()=>addBlock(b.dataset.addBlock)));$('blockComposer').addEventListener('change',e=>{const el=e.target.closest('[data-index][data-field]');if(!el)return;const block=state.blocks[Number(el.dataset.index)];if(el.dataset.field==='kind')switchBlockKind(block,el.value);else if(el.dataset.field==='length')block.length=Number(el.value)||1;else block[el.dataset.field]=el.value;renderBlocks();scheduleSave()});$('blockComposer').addEventListener('input',e=>{const el=e.target.closest('[data-index][data-field]');if(!el||el.dataset.field==='kind')return;const block=state.blocks[Number(el.dataset.index)];block[el.dataset.field]=el.dataset.field==='length'?(Number(el.value)||1):el.value;schedulePreview();scheduleSave()});$('blockComposer').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const i=Number(b.dataset.index),action=b.dataset.action;if(action==='delete')state.blocks.splice(i,1);if(action==='duplicate')state.blocks.splice(i+1,0,{...state.blocks[i]});if(action==='left'&&i>0)[state.blocks[i-1],state.blocks[i]]=[state.blocks[i],state.blocks[i-1]];if(action==='right'&&i<state.blocks.length-1)[state.blocks[i+1],state.blocks[i]]=[state.blocks[i],state.blocks[i+1]];renderBlocks();scheduleSave()});document.querySelectorAll('[data-binding]').forEach(b=>b.addEventListener('click',()=>{state.binding=b.dataset.binding;renderBinding();schedulePreview();scheduleSave()}));$('quickPatterns').addEventListener('click',e=>{const b=e.target.closest('[data-quick]');if(!b)return;b.dataset.quick==='unlimited'?addBlock('unlimited'):b.dataset.quick==='custom'?addBlock('custom'):addBlock('common',b.dataset.quick)})}

function bindHistoryEvents(){$('historySearch').addEventListener('input',renderHistory);$('historyStatus').addEventListener('change',renderHistory);$('historyBody').addEventListener('change',e=>{const input=e.target.closest('[data-history-domain]');if(!input)return;input.checked?state.selectedHistory.add(input.dataset.historyDomain):state.selectedHistory.delete(input.dataset.historyDomain);renderHistory()});$('historyCheckAll').addEventListener('change',e=>{state.visibleHistory.forEach(r=>e.target.checked?state.selectedHistory.add(r.domain):state.selectedHistory.delete(r.domain));renderHistory()});$('chooseHistoryExcel').addEventListener('click',async()=>{const r=await window.pywebview.api.choose_history_excel($('historyExcelPath').value);if(!r.ok){toast(r.message,'error');return}if(r.path){$('historyExcelPath').value=r.path;scheduleSave()}});$('exportHistory').addEventListener('click',async()=>{const r=await window.pywebview.api.export_history($('historyExcelPath').value);if(!r.ok){toast(r.message,'error');return}toast(`已导出 ${r.count} 条查询记录`,'success')});$('openHistoryExcel').addEventListener('click',async()=>{const r=await window.pywebview.api.open_history_excel($('historyExcelPath').value);if(!r.ok){toast(r.message,'error');return}toast(`已更新并打开 ${r.count} 条查询记录`,'success')});$('deleteSelectedHistory').addEventListener('click',async()=>{const count=state.selectedHistory.size;if(!count||!window.confirm(`确定删除选中的 ${count} 条已查询记录吗？\n删除后这些域名可以重新查询；已有 Excel 文件不会被删除。`))return;const r=await window.pywebview.api.delete_history([...state.selectedHistory]);if(!r.ok){toast(r.message,'error');return}state.selectedHistory.clear();applyHistoryResponse(r);toast(`已删除 ${r.deleted} 条记录，这些域名现在可以重新查询`,'success')});$('clearHistory').addEventListener('click',async()=>{if(!window.confirm(`确定清空全部 ${state.history.length} 条已查询记录吗？\n清空后所有域名都可以重新查询；已有 Excel 文件不会被删除。`))return;const r=await window.pywebview.api.clear_history();if(!r.ok){toast(r.message,'error');return}state.selectedHistory.clear();applyHistoryResponse(r);toast(`已清空 ${r.deleted} 条记录`,'success')})}

function bindEvents(){document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>setPage(b.dataset.page)));bindRuleEvents();bindHistoryEvents();$('siteSelect').addEventListener('change',()=>{const site=state.sites.find(x=>x.name===$('siteSelect').value);if(site){$('siteName').value=site.name;$('siteUrl').value=site.url;state.ready=false;setStatus('网站已改变，请重新连接','info');updateControls();scheduleSave()}});$('siteUrl').addEventListener('input',()=>{state.ready=false;setStatus('网站已改变，请重新连接','info');updateControls();scheduleSave()});['siteName','interval','retryInterval','limitTestsEnabled','limitTests','limitFoundEnabled','limitFound','runUntilStopped','excelPath','historyExcelPath','pageChoice'].forEach(id=>$(id).addEventListener('change',()=>{if(id==='interval')$('footerInterval').textContent=`${$('interval').value||0} 秒`;scheduleSave()}));$('saveSite').addEventListener('click',async()=>{const r=await window.pywebview.api.save_site({name:$('siteName').value,url:$('siteUrl').value});if(!r.ok){toast(r.message,'error');return}state.sites=r.sites;renderSites($('siteName').value);toast('网站已保存','success')});$('deleteSite').addEventListener('click',async()=>{const r=await window.pywebview.api.delete_site($('siteName').value);if(!r.ok){toast(r.message,'error');return}state.sites=r.sites;const s=state.sites[0];$('siteName').value=s.name;$('siteUrl').value=s.url;renderSites(s.name);toast('网站已删除','success')});$('connectChrome').addEventListener('click',connectChrome);$('reconnectPage').addEventListener('click',connectChrome);['topStart','bottomStart'].forEach(id=>$(id).addEventListener('click',startSearch));$('topPause').addEventListener('click',pauseSearch);$('topResume').addEventListener('click',resumeSearch);$('topStop').addEventListener('click',stopSearch);$('chooseExcel').addEventListener('click',async()=>{const r=await window.pywebview.api.choose_excel($('excelPath').value);if(!r.ok){toast(r.message,'error');return}if(r.path){$('excelPath').value=r.path;scheduleSave()}});['openExcel','resultOpenExcel'].forEach(id=>$(id).addEventListener('click',async()=>{const r=await window.pywebview.api.open_excel($('excelPath').value);if(!r.ok)toast(r.message,'error')}));['openFolder','resultOpenFolder'].forEach(id=>$(id).addEventListener('click',()=>window.pywebview.api.open_folder($('excelPath').value)));$('resultSearch').addEventListener('input',renderResults)}

async function initialize(){bindEvents();const initial=await window.pywebview.api.initial_state();state.patterns=initial.patterns;state.allowed=initial.allowed_characters;state.results=initial.results||[];state.history=initial.history||[];$('appVersion').textContent=`COM域名筛选器 v${initial.version}`;$('sideVersion').textContent=`版本 ${initial.version}`;applySettings(initial.settings);renderPatterns();renderResults();renderHistory();updateControls();refreshPreview()}
window.addEventListener('pywebviewready',initialize);
